# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisWnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalysisWnd(object):
    def setupUi(self, AnalysisWnd):
        AnalysisWnd.setObjectName("AnalysisWnd")
        AnalysisWnd.resize(614, 610)
        self.tableView = QtWidgets.QTableView(AnalysisWnd)
        self.tableView.setGeometry(QtCore.QRect(30, 170, 551, 411))
        self.tableView.setObjectName("tableView")
        self.comboBox = QtWidgets.QComboBox(AnalysisWnd)
        self.comboBox.setGeometry(QtCore.QRect(310, 30, 271, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(AnalysisWnd)
        self.label.setGeometry(QtCore.QRect(30, 30, 271, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.RunAnalysis = QtWidgets.QPushButton(AnalysisWnd)
        self.RunAnalysis.setGeometry(QtCore.QRect(30, 100, 551, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(24)
        self.RunAnalysis.setFont(font)
        self.RunAnalysis.setObjectName("RunAnalysis")

        self.retranslateUi(AnalysisWnd)
        self.RunAnalysis.clicked.connect(AnalysisWnd.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AnalysisWnd)

    def retranslateUi(self, AnalysisWnd):
        _translate = QtCore.QCoreApplication.translate
        AnalysisWnd.setWindowTitle(_translate("AnalysisWnd", "统计分析"))
        self.label.setText(_translate("AnalysisWnd", "请选择分析维度："))
        self.RunAnalysis.setText(_translate("AnalysisWnd", "启动分析引擎"))
