# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWnd(object):
    def setupUi(self, MainWnd):
        MainWnd.setObjectName("MainWnd")
        MainWnd.resize(346, 370)
        self.UL = QtWidgets.QPushButton(MainWnd)
        self.UL.setGeometry(QtCore.QRect(50, 30, 241, 81))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        self.UL.setFont(font)
        self.UL.setObjectName("UL")
        self.VL = QtWidgets.QPushButton(MainWnd)
        self.VL.setGeometry(QtCore.QRect(50, 130, 241, 91))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        self.VL.setFont(font)
        self.VL.setObjectName("VL")
        self.Analysis = QtWidgets.QPushButton(MainWnd)
        self.Analysis.setGeometry(QtCore.QRect(50, 250, 241, 91))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        self.Analysis.setFont(font)
        self.Analysis.setObjectName("Analysis")

        self.retranslateUi(MainWnd)
        self.UL.clicked.connect(self.UserLogin)  # type: ignore
        self.VL.clicked.connect(self.VideoLogin)  # type: ignore
        self.Analysis.clicked.connect(self.AnalysisFun)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWnd)

    def retranslateUi(self, MainWnd):
        _translate = QtCore.QCoreApplication.translate
        MainWnd.setWindowTitle(_translate("MainWnd", "短视频推荐系统 & By Krxk"))
        self.UL.setText(_translate("MainWnd", "用户登录"))
        self.VL.setText(_translate("MainWnd", "视频登录"))
        self.Analysis.setText(_translate("MainWnd", "统计分析"))

    def UserLogin(self):
        print('login user')

    def VideoLogin(self):
        print('login video')

    def AnalysisFun(self):
        print('analysis')
