# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userlogin(object):
    def setupUi(self, userlogin):
        userlogin.setObjectName("userlogin")
        userlogin.resize(330, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(userlogin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(userlogin)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(userlogin)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.login = QtWidgets.QPushButton(self.widget_2)
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.back = QtWidgets.QPushButton(self.widget_2)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(userlogin)
        self.login.clicked.connect(self.login) # type: ignore
        self.back.clicked.connect(self.GoBack()) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(userlogin)

    def retranslateUi(self, userlogin):
        _translate = QtCore.QCoreApplication.translate
        userlogin.setWindowTitle(_translate("userlogin", "短视频推荐算法"))
        self.label.setText(_translate("userlogin", "用户编号："))
        self.login.setText(_translate("userlogin", "登录"))
        self.back.setText(_translate("userlogin", "返回"))

    def GoBack(self):
        self.close()
        pass

    def Login(self):
        print('登录')
        pass
