# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videologin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vediologin(object):
    def setupUi(self, vediologin):
        vediologin.setObjectName("vediologin")
        vediologin.resize(330, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(vediologin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(vediologin)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(vediologin)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.login = QtWidgets.QPushButton(self.widget_2)
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.back = QtWidgets.QPushButton(self.widget_2)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(vediologin)
        self.login.clicked.connect(vediologin.raise) # type: ignore
        self.back.clicked.connect(vediologin.raise) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(vediologin)

    def retranslateUi(self, vediologin):
        _translate = QtCore.QCoreApplication.translate
        vediologin.setWindowTitle(_translate("vediologin", "Form"))
        self.label.setText(_translate("vediologin", "视频编号："))
        self.login.setText(_translate("vediologin", "登录"))
        self.back.setText(_translate("vediologin", "返回"))
