# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video(object):
    def setupUi(self, video):
        video.setObjectName("video")
        video.resize(326, 273)
        self.back = QtWidgets.QPushButton(video)
        self.back.setGeometry(QtCore.QRect(219, 207, 81, 31))
        self.back.setObjectName("back")

        self.retranslateUi(video)
        self.back.clicked.connect(self.DisplayVideo) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(video)

    def retranslateUi(self, video):
        _translate = QtCore.QCoreApplication.translate
        video.setWindowTitle(_translate("video", "Form"))
        self.back.setText(_translate("video", "返回"))

    def DisplayVideo(self):
        pass
