# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(330, 260)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/background.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Widget.setWindowIcon(icon)
        Widget.setAutoFillBackground(False)
        Widget.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.userLogin = QtWidgets.QPushButton(Widget)
        self.userLogin.setObjectName("userLogin")
        self.horizontalLayout.addWidget(self.userLogin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.videoLogin = QtWidgets.QPushButton(Widget)
        self.videoLogin.setObjectName("videoLogin")
        self.horizontalLayout.addWidget(self.videoLogin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(Widget)
        self.userLogin.clicked.connect(Widget.raise) # type: ignore
        self.videoLogin.clicked.connect(Widget.raise) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "短视频推荐算法"))
        self.userLogin.setText(_translate("Widget", "用户登录"))
        self.videoLogin.setText(_translate("Widget", "视频登录"))
