# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene

class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(748, 521)
        self.graphicsView = QtWidgets.QGraphicsView(Welcome)
        self.graphicsView.setGeometry(QtCore.QRect(220, 140, 281, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Welcome)
        self.label.setGeometry(QtCore.QRect(90, 30, 581, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Welcome)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 331, 61))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Welcome)
        self.label_3.setGeometry(QtCore.QRect(190, 430, 391, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")



        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "欢迎页 && By Krxk"))
        self.label.setText(_translate("Welcome", "欢迎使用短视频推荐系统"))
        self.label_2.setText(_translate("Welcome", "核心开发者：黎斌雄"))
        self.label_3.setText(_translate("Welcome", "正在为您加载核心数据......"))

        frame = QImage("core_developer.jpg")
        pix = QPixmap.fromImage(frame)
        item = QGraphicsPixmapItem(pix)
        scene = QGraphicsScene()
        scene.addItem(item)
        self.graphicsView.setScene(scene)

